version: "2.0"
services:
  api:
    build: ./api
    volumes:
      - ./api:/api
      - dist:/dist
      - /api/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: "0.0.0.0"

  terraform:
    build: ./terraform
    volumes:
      - ./terraform:/terraform
      - dist:/dist
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

volumes:
  dist:
