version: '2.0'
services:
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./tmp/dist:/tmp/dist
      - /api/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: fake-local-key
      AWS_SECRET_ACCESS_KEY: fake-local-secret
      PORT: 3000
      HOST: '0.0.0.0'

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./tmp/dynamodb:/data
