version: '2.0'
services:
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./tmp/dist:/tmp/dist
      - /api/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: fake-local-key
      AWS_SECRET_ACCESS_KEY: fake-local-secret
      AUTH_GITHUB_CLIENT_ID: '${AUTH_GITHUB_CLIENT_ID}'
      AUTH_GITHUB_CLIENT_SECRET: '${AUTH_GITHUB_CLIENT_SECRET}'
      ADMIN_EMAILS_CSV: '${ADMIN_EMAILS_CSV}'
      PORT: 3000
      HOST: '0.0.0.0'

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./tmp/dynamodb:/data

  ui:
    build: ./ui
    volumes:
      - ./ui:/ui
      - /ui/node_modules
      - /ui/resources
    depends_on:
      - api
    ports:
      - '1313:1313'
    environment:
      HUGO_ENV: 'development'
