name: Pre-deploy

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Pre-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Build API
        run: docker-compose run api run build

      - name: Run API tests
        run: docker-compose run api test

      - name: Initialize terraform
        run: docker-compose run terraform init
        if: github.repository_owner == 'adunkman'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Output terraform plan
        run: docker-compose run terraform plan
        if: github.repository_owner == 'adunkman'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
